### ISSUE TITLE
esbuild plugin does not handle esbuild entrypoint objects correctly

### ISSUE THREAD

**Issue by Cldfire** [DataDog/build-plugin#60]
Create [an in/out entrypoint object](https://esbuild.github.io/api/#entry-points) in your esbuild config:

```ts
const bundlerCtx = await esbuild.context({
	// ...
	entryPoints: [
		{
			in: "some/file.ts",
			out: "some/file",
		},
	],
	// ...
});
```

The DataDog esbuild plugin throws an error when trying to call `.replace` on that entrypoint object (presumably expecting it to be a string):

https://github.com/DataDog/build-plugin/blob/c1825702cf74e85a57d59d2a060ccff7042a1aa2/src/hooks/datadog/metrics/esbuild.ts#L32

```
[BuildPlugin] Couldn't aggregate metrics: TypeError: fullPath.replace is not a function
    at getModulePath (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/hooks/datadog/metrics/esbuild.js:27:31)
    at exports.getIndexed (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/hooks/datadog/metrics/esbuild.js:38:31)
    at getEsbuildMetrics (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/hooks/datadog/aggregator.js:28:24)
    at exports.getMetrics (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/hooks/datadog/aggregator.js:54:25)
    at BuildPluginClass.<anonymous> (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/hooks/datadog/index.js:36:36)
    at Generator.next (<anonymous>)
    at ./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/hooks/datadog/index.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/hooks/datadog/index.js:7:12)
    at BuildPluginClass.output (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/hooks/datadog/index.js:32:12)
    at applyHook (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/BaseClass.js:75:59)
    at BuildPluginClass.<anonymous> (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/BaseClass.js:86:19)
    at Generator.next (<anonymous>)
    at ./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/BaseClass.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/BaseClass.js:7:12)
    at BuildPluginClass.applyHooks (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/BaseClass.js:70:16)
    at BuildPluginClass.<anonymous> (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/esbuild/index.js:49:24)
    at Generator.next (<anonymous>)
    at ./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/esbuild/index.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/esbuild/index.js:7:12)
    at ./node_modules/.pnpm/@datadog+build-plugin@1.0.4_esbuild@0.20.1_webpack@5.90.1/node_modules/@datadog/build-plugin/dist/esbuild/index.js:31:33
    at ./node_modules/.pnpm/esbuild@0.20.1/node_modules/esbuild/lib/main.js:1496:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This prevents much of the plugin from working.

**Comment by yoannmoinet** [comment]
Thanks for the heads up, sorry for the delay.
We're currently revamping the plugin, and this will be covered in the next major release.

**Comment by yoannmoinet** [comment]
Fixed in v2.
